### ISSUE TITLE
BIM_KEY

### ISSUE THREAD

**Issue by 3d-consulting** [kbruxvoort/SSG.extension#5]
![image](https://github.com/kbruxvoort/SSG.extension/assets/18681426/195169f9-0526-4ebb-95a9-a0c4e443708d)
Hi Keep getting this alert, how to get rid of it and  declare the BIM_Key , Thanks

**Comment by kbruxvoort** [comment]
The tools in API requests are connecting to our internal database using a REST api. You need a token to use the API. This is only open to specific people at this moment, but it might get opened up to the public later.
